# Introducción a la programación con Python y Estructuras basicas

Python es un lenguaje de programación de alto nivel (sintaxis simple), interpretado, interactivo y orientado a objetos:

* **Interpretado**: Python es procesado al momento de la ejecución por el interpretador. No se necesita de un proceso previo de compilación para la posterior ejecución del programa.

* **Interactivo**: Podemos interactuar con el intérprete directamente para escribir los programas.

* **Orientado a objetos**: Python es un lenguaje orientado a objetos, una técnica de programación que encapsula el código dentro de objetos.

**Ejecutando código de Python**

Existen diferentes maneras de ejecutar código de Python, ya sea en Visual Studio Code, siendo este uno de los editores de código mas populares y de uso libre, pero en la ciencia de datos resulta siendo más útili utilizar los Notebooks, nosotros usaremos un enfoque interactivo proporcionado por los *Notebooks de Jupyter*. 

## Tipos datos de datos básicos

In [1]:
## codigo en C#
int numero;
numero = 6;

## Codigo C++
int numero;
numero = 6;

SyntaxError: invalid syntax (Temp/ipykernel_1472/3360332986.py, line 2)

In [ ]:
## Sintaxis de python
numero = 6

In [ ]:
#numero enteros
numero_entero = 8  #---> tipo int

#numeros decimales float
numero_decimal = 7.232 # ---> tipo float

#Datos booleanos
dato_bool = True # ---> tipo bool
dato_bool = False

#Dato string o cadena de caracteres 
dato_string = "python" # ---> tipo str
dato_string = " "
dato_string = "python version 3.8"
dato_string = 'python version 3.8'

# Palabras claves reservadas

Ahora hablemos de lo que son algunos objetos en python. Las variables.
Los nombres de las variables en Python pueden contener caracteres alfanuméricos *a-z*, *A-Z*, *0-9* y algunos caracteres especiales como _. Los nombres de las variables deben comenzar con una letra. 

Por convención, los nombres de las variables comienzan con letras minúsculas, y los nombres de las Clases con letras mayúsculas.

Adicionalmente, existe un número de palabras claves que no pueden ser usadas como nombres de variables. Estas palabras claves son:

```Python
and, as, assert, break, class, continue, def, del, elif, else, except, exec, finally, for, from, global, if, import, in, is, lambda, not, or, pass, print, raise, return, try, while, with, yield, type
```
Las palabras clave se reconocen porque todas se "ponen" de color verde


In [ ]:
# como ejecutar una celda de codigo con el teclado
# enter + shift
# enter + ctrl

In [ ]:
variable_1 = 0

# continue = 342432  ----> evitar este tipo de asignaciones a las palabras reservadas

# Listas

En esta sección se presenta uno de los tipos integrados más útiles de Python, las **listas**.

Al igual que un **string**, una lista es una secuencia de valores. En un string los valores son caracteres; en una **lista**, se puede tener **cualquier tipo**. Los **valores de una lista** se denominan **elementos**.

Hay varias formas de crear una nueva lista; la forma más simple es encerrar los elementos entre corchetes `[a,b,c]`:

In [ ]:
lista = [122, 21312, 1231]
lista_aux = [1212, "hola", "Eafit", True, False]
lista_aux_2 = [1212, "hola", "Eafit", True, False, [23, "1152892322", ["David", "Piedrahita", "Florez"]]]

In [ ]:
lista_aux

In [ ]:
lista_aux_2

## Consultar el tipo de dato

In [2]:
num = 5
type(num)

int

In [3]:
num = 5.9
type(num)

float

In [4]:
palabra = "texto"
type(palabra)

str

In [5]:
type(lista_aux_2)

NameError: name 'lista_aux_2' is not defined

# Manipular listas

- Consultar metodos de listas: https://docs.python.org/es/3/tutorial/datastructures.html

Para acceder a los elementos de la lista lo hacemos mediante siguiendo la indexación 

`listas[0]`$\rightarrow$ elemento 1 de la lista.

`listas[1]`$\rightarrow$ elemento 2 de la lista.

`listas[2]`$\rightarrow$ elemento 3 de la lista.

`listas[3]`$\rightarrow$ elemento 4 de la lista.

Acceder a un rango determinado de datos dentro de la lista:

`listas[0:3]`$\rightarrow$ elemento 0 al elemento 3

Acceder al último elemento de lista:

`listas[-1]`$\rightarrow$ elemento final de la lista


In [ ]:
lista_num = [122, 21312, 1231]

In [ ]:
lista_num[0]

In [ ]:
lista_num[1]

In [ ]:
lista_num[2]

In [ ]:
lista_num[3]

In [ ]:
lista_num

In [ ]:
lista_num[-1]

In [ ]:
lista_num[-2]

In [ ]:
lista_num[-3]

## Extraer multiples elementos de una lista

In [ ]:
lista_num_2 = ["hola", "mundo", "python", "eafit", "Datos"]
#                0        1        2         3        4
lista_num_2

In [ ]:
lista_num_2[0:3]

In [ ]:
lista_num_2[3:5]

In [ ]:
lista_num_2[3:4]

In [ ]:
lista_num_2[3]

## Extraer elementos de una lista dentro de una lista

In [ ]:
lista_aux_1 = [1212, "hola", "Eafit", True, False]
lista_aux_2 = [1212, "hola", "Eafit", True, False, [23, "1152892322"]]
lista_aux_3 = [1212, "hola", "Eafit", True, False, [23, "1152892322", ["David", "Piedrahita", "Florez"]]]

In [ ]:
lista_aux_2[5][0]

In [ ]:
lista_aux_3[5][2][1]

# Diccionario

Los diccionarios son también parecidos a las listas, excepto que cada elemento es una pareja clave y valor. La sintaxis en los diccionarios es de la forma 

```Python
diccionario = {
    "clave_1" : valor1, 
    "clave_2" : valor2,
         .         .
         .         .
         .         .
         .         .,
    "clave_N" : valorN
}
```

El valor de cada clave puede ser desde un valor numerico hasta datos como listas, arrays y hasta DataFrames

In [ ]:
diccionario_num = {
    "numero_decimal": 3.7 
}

diccionario_num

In [ ]:
diccionario_num = {
    "numero_decimal": 3.7,
    "numero_entero": 44
}

print(diccionario_num)
type(diccionario_num)

In [ ]:
# int
# float
# bool
# str
# list
# dict

In [ ]:
dict_1 = {
    "ciudades": ["Medellin", "Cartagena", "Popayan"],
    "departamentos": ["Antioquia", "Bolivar", "Cauca"],
    "pais": ["Colombia"],
    "pueblos": ["Santa Fe"]
}

dict_1

# Manipular diccionarios

In [ ]:
print(dict_1["ciudades"])
print(dict_1["departamentos"])

In [ ]:
dict_1["departamentos"][1]

In [ ]:
dict_1["pais"][0]

In [ ]:
dict_1["departamentos"]

In [ ]:
dict_2 = {
    "ciudades": dict_1["ciudades"],
    "departamentos": dict_1["departamentos"]
}

dict_2

## Consultar llaves del diccionario

In [ ]:
y = 3

In [ ]:
dict_1.keys()

In [ ]:
dict_1.values()

In [ ]:
dict_1.items()

In [ ]:
dict_1.clear()
dict_1

In [ ]:
dict_1["pais"]

# Estructura if, elif y else

## If
If para python es un condicional. Algunos autores lo llamarán una estructura de control, con lo cual solo quieren ilustrar lo que se ha querido decir en la definición de condicional. Esta estructura permite que un programa ejecute unas instrucciones cuando se cumplan una condición. Es importante notar la palabra "if" en inglés traduce "si" como condición, no "sí" como afirmación.

La sintaxis del condicional if es



```Python
if condición :
    <bloque de codigo a ejecutar si la condicion se cumple>
```


In [ ]:
## c#

if (3 == 4){
    Console.Write("Hola mundo")
}

## C++
if (3 == 4){
    printf("Hola mundo")
}

In [ ]:
#si 3 es igual a 4 entonces ejecute la linea de codigo

if 3 == 4:
    print("Los dos numeros son iguales")

if 4 == 4:
    print("Los dos numeros son iguales")

### Ejercicio

Hacer un programa que imprima en pantalla si un numero es positivo o negativo o neutro

In [ ]:
numero_1 = int(input("Imgrese un numero: "))
# numero_1 = float(input("Imgrese un numero: "))

if numero_1 > 0:
    print("El numero es positivo")
    
if numero_1 < 0:
    print("El numero es negativo")
    
if numero_1 == 0:
    print("El numero es neutro")   

## Else
Suponga ahora que se desea ejecutar un bloque de código dado que la condición inicial sea falsa, para esto se usa el comando `else`, el cual se ejecuta siempre y cuando la condición del `if` no se cumpla.

```Python
if cond :
    <bloque de codigo a ejecutar si la condicion se cumple>
else :
    <bloque de codigo a ejecutar si la condicion no se cumple>
```


In [ ]:
numero_1 = 34

if numero_1 > 0:                     # va a ecjutar esto
    print("El numero es positivo")
    
if numero_1 < 0:                     # va a ecjutar esto
    print("El numero es negativo")

In [ ]:
numero_1 = int(input("Imgrese un numero: "))

if numero_1 > 0:
    print("El numero es positivo")
else:
    print("El numero es negativo")

## Elif
Suponga que desea ahora imponer una condición ante la negación de la primera afirmación. Es decir, si la primera primera condición resultó falsa necesito formular otra condición. En este caso usamos el condicional `elif`. Este nace de la conjunción de `else` y `if`. Veamos su sintaxis.

```python
if cond1 :
    <bloque de codigo a ejecutar si la condicion se cumple>
    
elif cond2:
    <bloque de codigo a ejecutar si la condicion del if no se cumple, pero la condicion del elif debe cumplirse> 
```

Veámoslo con nuestro ejemplo.

In [ ]:
# Comentar todas las lineas de codigo: ctrl + llaves

In [ ]:
numero = float(input("ingrese un numero: "))

if numero > 0:
    print("Es positivo")
    
elif numero < 0:
    print("Es negativo")

elif numero == 0:
    print("Es neutro")

In [ ]:
## Con el else
numero = float(input("ingrese un numero: "))

if numero > 0:
    print("Es positivo")
    
elif numero < 0:
    print("Es negativo")

else:
    print("Es neutro")

# Loops, ciclos o bucles

Hemos visto que un condicional es una decisión sobre una sentencia. Ahora nos ocuparemos de los ciclos. Podríamos pensar que un loop, ciclo o bucle es un bloque que se ejecuta continuamente mientras se cumpla una condición.

## For

El ciclo `for` es el más usual de todos. Su uso es fácil, se llama una variable y se itera en un bloque de código mientras se cumpla dicha condición sumándole cada vez un valor llamado `step`. Es válido notar que el bloque no debe depender de dicha variable o contador.

La sintaxis en Python es la siguiente:

```Python
for contador in range (inicio, fin, step):
    <bloque de código a ejecutar>
```

In [ ]:
range(0, 10)

In [ ]:
# sintaxis en C++

for(int i; i<10; i++){
    
}

In [ ]:
for i in range(0, 10):
    print("Hola")

Cabe resaltar que las listas son elementos que se peuden iterar dentro de un ciclo `for` como veremos a continuación:

el iterador es aquel dato que contiene multiples elementos que podemos utilizar como ietradores del ciclo

```Python
for contador in <iterador>:
    <bloque de código a ejecutar>
```

In [ ]:
lista_ciudades = ["Medellin", "Cartagena", "Manizales"]

for ciudad in lista_ciudades:
    print(ciudad)

In [ ]:
dict_city = {
    "ciudades": ["Medellin", "Cartagena", "Manizales"],
    "departamentos": ["Antioquia", "Bolivar", "Caldas"],
    "pueblos": ["La Union", "Rionegro", "Cartago"]
}

for key in dict_city.keys():
    print(dict_city[key])

# Uso del metodo print

In [ ]:
numero = int(input("ingrese un numero: "))
print("hola mundo")
print(numero)

In [ ]:
numero = int(input("ingrese un numero: "))
print("El numero que usuario ingreso es:", numero)

In [ ]:
numero = input("ingrese un numero: ")
print("El numero que usuario ingreso es: " + numero)

In [ ]:
numero = input("ingrese un numero: ")
palabra = input("ingrese una palabra: ")
print(f"El numero que usuario ingreso es: {numero}")

Pdemos tener además tener un `for` dentro de otro `for`, de la siguiente forma

In [ ]:
ciudades = ["Medellin", "Villavicencio"]

In [ ]:
for i in range(0, 10):
    
    if i > 9:
        print("El ciclo termino")
        
        if i < 20:
            print("El ciclo se ejecuto menos de 20 veces")
            
    for i in ciudades:
        
        print(f"Estas son las ciudades {i}")

# Modulo Numpy

Numpy es un paquete fundamental para el trabajo científico en python:
* Contiene Funciones, módulos, clases y cierto tipo especial de datos. 
* Permite el manejo de Arrays Multidimensionales. 
* Contiene Funciones sofisticadas y optimizadas. Permite incorporar códigos en C/C++ o fortran. 
* Contiene un paquete de álgebra lineal y permite hacer cálculos estadísticos, ajustes, interpolación entre otras.


> El tipo de dato mas importante en numpy es el **array**. El array es un tipo de dato, formado a partir de otro tipo de datos mas sencillos y que estan ordenados en una secuencia definida, en ese sentido es muy similar a una lista o tupla, pero a diferencia de estos, un array solo admite un tipo de dato.

- Consultar documentación: https://numpy.org/doc/stable/reference/arrays.html#

In [ ]:
# alternativa 1
# import numpy

In [ ]:
## C#

for (condicon):
    for
        for

In [6]:
# alternativa 2
import numpy as np

In [ ]:
### instalar un paquete
## pip install nombre_paquete

## Crear un array

Un array puede ser creado mediante el uso de datos nativos de python (listas, tuplas,datos
básicos) usando la función **numpy.array()**:

```python
numpy.array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
```
Donde podemos especificar el tipo de datos con *dtype*, el orden con *order* (esto hace referencia el modo "C", por filas, o "F", por columnas, para el diseño de memoria del arreglo. Generalmente se deja en "K" para que automaticamente escoja la mejor opción), la dimensión miníma puede establecerse con con *ndmin*.

## Crear un numpy array

In [9]:
lista_num = [1, 2, 3, 4]
arreglo = numpy.array(lista_num) 
arreglo

NameError: name 'numpy' is not defined

In [ ]:
lista_num = [1, 2, 3, 4]
arreglo = np.array(lista_num)
arreglo

In [ ]:
x = np.array([4,5,6]) 
x

## Arrays de mas de una dimension

Es importante observar que lso arrays pueden tener tanto filas como columnas queramos

In [10]:
lista_num_1 = [[1,2,3], [4,5,6], [7,8,9]]
arreglo_2 = np.array(lista_num_1)
arreglo_2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Observe que si intenta crear un array donde una de las filas contiene mas columnas que las demas el array no podrá crearse correctamente

In [11]:
lista_num_2 = [[1, 2, ], [4, 5, 6], [7, 8, 9]]
arreglo_3 = np.array(lista_num_2)
arreglo_3

C:\Users\DAVID~1.PIE\AppData\Local\Temp/ipykernel_1472/3986971587.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arreglo_3 = np.array(lista_num_2)


array([list([1, 2]), list([4, 5, 6]), list([7, 8, 9])], dtype=object)

In [12]:
list_names = ["Juan", "Sara"]
arreglo_4 = np.array(list_names)
arreglo_4

array(['Juan', 'Sara'], dtype='<U4')

In [13]:
# int ---> int8, int32, int64
# float -> float8, float32, float64

In [14]:
lista = ["palabra", 1]
lista

['palabra', 1]

In [15]:
arreglo_5 = np.array(lista)
arreglo_5

array(['palabra', '1'], dtype='<U11')

# Atributos de un array

Los arrays pueden tener diferentes atributos, estos son algunos de los mas comunes:

- `shape`, `size`, `dtype`, `nbytes`

## Tamaño de un Array

In [16]:
arreglo_2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
arreglo_2.shape

(3, 3)

In [18]:
lista_num_4 = [[1, 2, 3, 56], [4, 5, 6, 55], [7, 8, 9, 99]]
arreglo_4 = np.array(lista_num_4)
arreglo_4

array([[ 1,  2,  3, 56],
       [ 4,  5,  6, 55],
       [ 7,  8,  9, 99]])

In [19]:
arreglo_4.shape

(3, 4)

## Numero de elementos del array

In [20]:
arreglo_4.size

12

## Tipo de datos dentro del array

In [21]:
type(arreglo_4)

numpy.ndarray

In [22]:
arreglo_4.dtype

dtype('int32')

In [23]:
c = np.array([1,2,3], dtype = "int64")
c.dtype

dtype('int64')

## Tamaño en bytes

In [24]:
arreglo_4

array([[ 1,  2,  3, 56],
       [ 4,  5,  6, 55],
       [ 7,  8,  9, 99]])

In [25]:
arreglo_4.nbytes

48

# Algunos métodos de numpy

Los métodos de un array nos permiten realizar algunas de sus funcionalidades como veremos acontinuación:

## Transpuesta de un array

In [26]:
arreglo_4

array([[ 1,  2,  3, 56],
       [ 4,  5,  6, 55],
       [ 7,  8,  9, 99]])

In [27]:
arreglo_4.T

array([[ 1,  4,  7],
       [ 2,  5,  8],
       [ 3,  6,  9],
       [56, 55, 99]])

In [28]:
arreglo_4.transpose()

array([[ 1,  4,  7],
       [ 2,  5,  8],
       [ 3,  6,  9],
       [56, 55, 99]])

In [ ]:
type(arreglo_4)

In [30]:
lista = [1,2,3,4]
len(lista)

4

## np.arange()

In [ ]:
lista_num_4 = [[1, 2, 3, 56], [4, 5, 6, 55], [7, 8, 9, 99]]
arreglo_4 = np.array(lista_num_4)
arreglo_4

In [39]:
np.arange(start = 2, stop = 50, step = 10, dtype = "float64")

array([ 2., 12., 22., 32., 42.])

In [42]:
np.arange(stop = 50, start = 2, step = 10, dtype = "float64")

array([ 2., 12., 22., 32., 42.])

In [41]:
np.arange(50, 2, 10)

array([], dtype=int32)

## np.linspace

In [ ]:
# np.linspace(start, stop, num = 50)

In [49]:
np.linspace(start = 1, stop = 50, num = 8)

array([ 1.,  8., 15., 22., 29., 36., 43., 50.])

## np.random.rand()

In [ ]:
# np.random.rand(rows, columns) me crea una arreglo de nxm con numeros aleatorios entre 0 y 1


In [60]:
np.random.rand(5, 3)*10

array([[3.23720536, 7.47311569, 8.25860309],
       [9.83487149, 0.27381456, 1.44975849],
       [7.84007436, 4.78177974, 0.86889258],
       [7.44657942, 5.50949437, 6.66201364],
       [6.48499417, 9.74182702, 6.32282525]])

In [61]:
np.random.rand(5, 3)*100

array([[61.29475385, 10.35135008, 64.96962915],
       [99.71674738, 55.89606293, 69.62535912],
       [98.50828413, 32.49291069, 75.23956898],
       [39.50529197,  9.78292332, 76.8430657 ],
       [77.4471607 , 74.00593644, 28.63568879]])

## Crear arreglos de unos y ceros

In [62]:
np.array([1,1,1,1,1,1])

array([1, 1, 1, 1, 1, 1])

In [68]:
np.ones(shape = (5, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [71]:
np.zeros(shape = (5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

## numpy.random.uniform()

In [77]:
np.random.uniform(1, 50, 30)

array([ 9.65555725, 18.17399038, 46.49127112, 22.23970533, 31.76628839,
       22.38319465, 27.32305667, 43.6057375 , 14.23076523,  1.04278293,
       23.79786157, 44.53754414, 40.98093173, 41.97316611, 38.51982979,
       34.46094323, 15.13240399,  8.7988652 , 40.26729211, 36.63782697,
       24.00246087, 35.63774764, 37.14761253, 13.39509405, 15.18883548,
       12.38377329,  2.026576  ,  1.78287032, 33.91610611, 42.51814731])

## array metodo copy()

In [78]:
x = np.array([1,2,3])
y = x

In [80]:
y = x.copy()

In [81]:
y 

array([1, 2, 3])

### tener en cuenta:

In [82]:
lista = ["EAFIT", "Politecnico", "ITM"]
lista_ejemplo = lista

In [84]:
lista.append("Sena")
lista

['EAFIT', 'Politecnico', 'ITM', 'Sena']

In [85]:
lista_ejemplo

['EAFIT', 'Politecnico', 'ITM', 'Sena']

In [86]:
lista_copiar = lista.copy()
lista_copiar

['EAFIT', 'Politecnico', 'ITM', 'Sena']

In [87]:
lista.append("Pascual")
lista

['EAFIT', 'Politecnico', 'ITM', 'Sena', 'Pascual']

In [88]:
lista_copiar

['EAFIT', 'Politecnico', 'ITM', 'Sena']

In [ ]:
FuncionSuma

# Definicion de funciones

# Funciones
Usualmente en el desarrollo de un código debemos usar varias veces el mismo algoritmo, no necesariamente de forma periódica. Es fácil pensar que si quiero calcular un valor estadístico que no esté predefinido por algo el lenguaje de programación, tendremos que ir haciendo `Ctrl+C` y luego `Ctrl+V` del código como tantas veces lo necesitemos por todo nuestro código. Para evitar esto existen las funciones. Con ellas es posible desarrollar de forma ordenada el código y por consiguiente más entendible.

La sintaxis de una función es la siguiente:

```Python
def Nombre_de_la_funcion(arg1, arg2,...argn):
    bloque de código
    return valor_a_retornar #------> solo si se necesita que la funcion retorne un valor


# si no es necesario retornar un valor se puede escrbir así:
def nombre_funcion(arg1, arg2,...argn):
    bloque de código                    
```
En general es necesario el uso de `return` al final de cada función. De esa forma la función sabe exactamente qué debe devolver. 


In [1]:
def suma(numero_1, numero_2):
    print(numero_1 + numero_2)

In [5]:
x = suma(3, 5)
type(x)

8


NoneType

In [18]:
def suma_v2(num_1 = int, num_2 = int):
    return num_1 + num_2

In [19]:
variable = suma_v2(num_1 = 5.3, num_2 = 10.112)
variable

15.411999999999999

## Retornar mas de dos valores

In [34]:
def suma_resta_multiplicacion(num_1, num_2):
    
    suma = num_1 + num_2
    resta = num_1 - num_2
    multiplicar = num_1 * num_2
    
    return suma, resta, multiplicar

In [35]:
resultado = suma_resta_multiplicacion(2, 3)
resultado

(5, -1, 6)

In [37]:
resultado[2]

6

In [43]:
suma, resta, multiplicacion = suma_resta_multiplicacion(2, 3)

# Ejercicios propuestos

**Ejercicio 1**

Determine para un número entero cualquiera si es par o impar
- Utilice una sentencia if - else

**Ejercicio 2**:

Determine de un número cualquiera real entero positivo si es un número primo o no
- Tip: utilice un ciclo for para realizar dicha operación

**Ejercicio 3**:

Cree una lista con cualquier tipo de dato del tamaño que usted considere, a dicha lista agregue un dato utilizando el método append

**Ejercicio 4**:

Cree una lista con cualquier tipo de dato del tamaño que usted considere, a dicha lista elimine un dato utilizando algún método que permita hacerlo, consulte en el siguiente link los diferentes métodos asociados a las listas y busque el método apropiado:
- Métodos de las listas: https://docs.python.org/es/3/tutorial/datastructures.html

**Ejercicio 5:**

En un colegio personalizado del país, se tienen salones constituidos por 5 estudiantes. La lista de estudiantes de uno de ellos es:

```
kinderA_lista = ['Gómez, Sebastián', 'Arango, Natalia', 'Zambrano, Javier', 'Domingo, Carolina'] 
````

Organice dicha lista en orden alfabético, guardándola en la misma variable e imprímala en pantalla.

- tip: para resolver este ejercicio consulte de nuevo los métodos de las listas, allí encontrará un método que permita ordenar la lista

**Ejercicio 6:** 

La siguiente lista representa una pequeña base de datos constituida por pacientes de una clinica en la ciudad de Medellín. Cada paciente se identifica como:

```
ID_numero-Medellin
```
Por motivos de optimización, un programador en `python`requier extraer solamente el número de identificación de cada elemento de la lista. Realice la extracción del número elemento por elemento, de la siguiente lista:

```
pacientes = ["ID_0001-Medellin","ID_0002-Medellin","ID_0003-Medellin","ID_0004-Medellin"]
```

- tip: consulte la documentación del método split para dar solución al ejercicio: https://python-reference.readthedocs.io/en/latest/docs/str/split.html

**Ejercicio 7:**

Escriba un programa que permita calcular la suma de los 100 primeros números.

- tip: utilice un ciclo for para resolver el ejercicio, además consulte como utilizar un contador dentro de un ciclo

**Ejercicio 8:**

En matemáticas, la sucesión o serie de Fibonacci hace referencia a la secuencia ordenada de números descrita por Leonardo de Pisa, matemático italiano del siglo XIII:

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144,…]

A cada uno de los elementos de la serie se le conoce con el nombre de número de Fibonacci.

Realice un programa que permita calcular una lista que contenga la serie fibonacci hasta la posición 20 así:

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181]

- Para calcular el siguiente número de la serie `numero(k+1) = numero(k-1) + numero(k)`

- tip: utilice un ciclo for e inicialice una lista con los siguientes números [0, 1] antes de ejecutar el for

**Ejercicio 9:** 

Cree una función que solicite al usuario una palabra e imprima si esta es un palíndromo o no. (Un palíndromo es una palabra o frase que se lee igual hacia adelante y hacia atrás), por ejemplo:

- Anilina, note que la palabra al leerla de izuqierda a derecha y de derecha a izquierda es exactamante igual

- tip: para resolver el ejercicio consulte como invertir una cadena de caracteres
